### ISSUE TITLE
Feature Request: loading-component similar to loading-text

### ISSUE THREAD

**Issue by shyamal890** [ng2-ui/auto-complete#123]
Currently we can change the text displayed for loading purpose. With that, the end-user would also require an option to show custom html (spinner div, etc). Is it possible to have a `loading-component` / `loading-template`?

**Comment by allenhwkim** [comment]
Your requirement is not clear to me. Please be specific with an example.

**Comment by crh225** [comment]
I think what they are requesting is to have something like the list-formatter function, so they can display custom html instead of the loading text.

something like loading-formatter

**Comment by allenhwkim** [comment]
anyone who wants to take over this? I tried but failed with security errors.

**Comment by smitthakkar96** [comment]
Please refer PR #209

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
