### ISSUE TITLE
Dynamic source list does not updated when input in focus

### ISSUE THREAD

**Issue by erictraub** [ng2-ui/auto-complete#169]
I am trying to dynamically update the source list on every `keyup` but it does not work.  I must un-focus from the input then re-focus on it for the list to update.  The example below uses a setTimeout which functions in the same way as updating the source list on a `keyup`.

HTML: 
```
<div ng2-auto-complete 
      [source]="arrayOfStrings"
      (valueChanged)="valueChanged($event)"
      placeholder="enter text">
      <input [ngModel]="model1" />
</div>
```

In component: 

```
arrayOfStrings = ['this', 'is', 'list', 'of', 'string', 'element'];

ngOnInit() {
    setTimeout(() => {
      console.log('Source updated');
      this.arrayOfStrings = ['a', 'new', 'list', 'of', 'words'];
    }, 7000)
}
```

If you put these in [this plunker](http://plnkr.co/edit/3pB1Gx?p=preview) and focus on the input before the source is updated (before the setTimeout finishes), the list will not update for you.  It will only update when you de-focus the input (`blur`) then `focus` on it again.

How can I dynamically update the source list on every keyup (essentially the same thing that the setTimout in this example is doing) without having to `blur` then `focus` the input?

**Comment by allenhwkim** [comment]
Please use Observable source list for this case.

**Comment by allenhwkim** [comment]
Example
http://plnkr.co/edit/ExzNSh?p=preview

**Comment by marslan390** [comment]
There should be something to update list when source data array changed without observable.
