### ISSUE TITLE
Feature request: include/exclude fields of object from matching

### ISSUE THREAD

**Issue by mihilion** [ng2-ui/auto-complete#170]
Currently when matching is done, JSON.Stringify is run on entire object. This is causing problems, when objects have technical data (like IDs from database, which I do not want to clear, but I also do not want the autocomplete to compare them with the input).

Example:
var source = [{"id": 10001, "code": 100, "name": "First item"},
{"id": 10002, "code": 200, "name": "Second item"}];

When I write "100" inside the autocomplete box, I would like to see only the first element with code 100, but the second element is also matched, because "100" is part of its database id "10002".

Idea for a solution:
String @Input could be added with comma-separated field names, to be used as:
[included-fields-or-whatever-you-want-to-call-this-attribute]="code,name",
or the opposite one, to be used as:
[excluded-fields-or-whatever-you-want-to-call-this-attribute]="id".

Please let me know if you find this feature useful, and if you are going to implement it anytime soon.

**Comment by allenhwkim** [comment]
@mihilion Please use Observable source for custom listing.

**Comment by mihilion** [comment]
@allenhwkim Ok, thanks, I will check this approach. However, after thinking about it for a while, I have realized, that I simply want the keyword to be matched against the values which I really see on the list, and not against some hidden parts of the object. Since you already have a list-formatter, I have used it to implement my desired behavior by adding one simple boolean attribute. Feel free to check my pull request.

**Comment by allenhwkim** [comment]
@mihilion so, you only want to select what you can see, right?
Does your PR also covers `list-formatter` not only as a string but also as a function?

**Comment by mihilion** [comment]
@allenhwkim sure, I am using your function getFormattedList (which I have moved to Ng2AutoComplete so it could be used by the filter function, and renamed to getFormattedList**Item**, as it really returns one formatted item, not the whole list), so my PR preserves all the current and future logic for handling `list-formatter`.

**Comment by allenhwkim** [comment]
@mihilion thanks. I will test and publish when all are good.
