### ISSUE TITLE
first in the list is auto selected

### ISSUE THREAD

**Issue by saurabhkumar11** [ng2-ui/auto-complete#174]
When Start typing, first in the list is auto selected and hit the enter, text box is filled with first item. i did not want it to fill textbox on enter like Jquery Autocomplete.

go to : https://rawgit.com/ng2-ui/ng2-auto-complete/master/app/index.html
type 1-2 letters in textbox and see the list.
first item in the list is selected. now if i hit the enter, first item will be populated in textbox.

earlier i implemented the JQuery autocomplete. it did not select the first item in the list.

**Comment by allenhwkim** [comment]
I am not sure about this. Many people just want to ENTER to select the first item. I need feedbacks.

**Comment by saurabhkumar11** [comment]
Actually, this is the feature in our old application. Like, if i enter james in text box and got 3-4 suggestions in auto complete. Now we may need extra information, like Department, Region etc to find. So, we give them enter to search and card listing will open with other information. This is the additional feature we provide.

**Comment by ndcunningham** [comment]
This seems very specific. Hitting enter is a _natural_ way of selection unless stated otherwise and i think this was achieved.

**Comment by allenhwkim** [comment]
@ndcunningham Nico, @saurabhkumar11 is suggesting not to use ENTER key, but I agree to use ENTER key.

**Comment by ndcunningham** [comment]
i agree @allenhwkim
