### ISSUE TITLE
No result found does not inherit the custom style specified

### ISSUE THREAD

**Issue by lnrdnl** [ng2-ui/auto-complete#177]
**Reproduce:**
 - In the plunker example: http://plnkr.co/edit/0QFYFHMmCAFmhbYAGQl7?p=preview
 - Type 'aa'
 - The list displays only: 'No result found', but this is not readable.

**Current behavior:**

  - The 'No result found' list item does not inherit any custom styles given in ListFormatter

**Expected/desired behavior:**

  - The 'No result found' list item should be able to have any custom class defined to it.

**Other information:**

  - Maybe it is enough just to override the css of the component. Then any documentation on this would be helpful. I did not dig in it (yet), I just came across the problem.

**Comment by allenhwkim** [comment]
There is class `no-match-found`. Please make use of it.
![image](https://cloud.githubusercontent.com/assets/1437734/24732853/bd2191a0-1a41-11e7-91a2-4517586d9ee4.png)

**Comment by smitthakkar96** [comment]
@allenhwkim can we document these classes or create several properties to set this classes so that it becomes more convenient for people to use.

**Comment by allenhwkim** [comment]
@smitthakkar96 yes, plz go ahead

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
