### ISSUE TITLE
Applying custom format to ngui-auto-complete-wrapper not applied

### ISSUE THREAD

**Issue by javimudi** [ng2-ui/auto-complete#178]
Hi,

I'm adding some selectors to a bootstrapped design. And I'm applying a custom CSS for ngui-auto-complete-wrapper, specifically a value of 100% for width, since the selector is not fully expanded to the container.

```
.ngui-auto-complete-wrapper {
  width: 100%;
}
```
The style is not really working.

Thanks

**Comment by allenhwkim** [comment]
To override css, you need to use `ViewEncapsulation.None`
```
  // encapsulation: ViewEncapsulation.Native
  encapsulation: ViewEncapsulation.None
  // encapsulation: ViewEncapsulation.Emulated is default 
```

**Comment by javimudi** [comment]
Thanks, @allenhwkim !

I'll take a look and figure out how to change the behavior.

Regards

**Comment by raviji** [comment]
Where to edit/use this ` encapsulation: ViewEncapsulation.None`?

**Comment by sourcevitor** [comment]
@raviji  In your component 

@Component({
    selector: 'vm-autocomplete',
    template: `
    <input auto-complete [(ngModel)]="autocompleteModel" name="nameComponent">
    `,
    styleUrls: ['vm/component/vm-autocomplete/vm-autocomplete.css'],
    encapsulation: ViewEncapsulation.Emulated
})

**Comment by raviji** [comment]
@sourcevitor Thnx bro, will try this

**Comment by dodoshanti** [comment]
@javimudi Did this work for you?
Setting ViewEncapsulation.None doesn't work because ngui-auto-complete component styles loads after you click in the input box, which is after the parent styles have loaded.
The only way around this is using !important
