### ISSUE TITLE
Auto complete with Object.Object.Object....

### ISSUE THREAD

**Issue by polaris327** [ng2-ui/auto-complete#179]
I tried to use this component to autocomplete with sub properties. Like - `object.property1.property2`.
Auto complete feature with `Object.PropertyA` is working correctly but 2nd Array of object is not working.

I attached *Plunker Example* . Actually it is same with demo but only `list-formatter` input value is different.

How can I deal with in this case?

**Steps to reproduce and a minimal demo**
  - _Plunker example - http://plnkr.co/edit/uJqPXv?p=preview
  - try to type in input box to use *AutoCompleteList* then you can see incorrect list is displaying.

**Current behavior**

  - Not working with `Object.PropertyA.PropertyB`

**Expected/desired behavior**

  - Correct working as Demo. http://plnkr.co/edit/ExzNSh?p=preview

**Other information**

  - If you check plunker then you can notice what I am saying. Kindly review this issue and help me.

Best regards
Polaris.

**Comment by allenhwkim** [comment]
`pathToData` does not work?
https://github.com/ng2-ui/auto-complete/blob/master/src/auto-complete.component.ts#L219

**Comment by allenhwkim** [comment]
For your case, please use `[list-formatter]` as a function. Example http://plnkr.co/edit/r1ybFl?p=preview.

**Comment by polaris327** [comment]
Hi @allenhwkim 

Thanks for your comment. I can see correct dropdown list now. 
But there is another problem. When I select an item from the list, it says just "undefined".  So autocomplete feature seems to not working correctly. 
Any idea about this issue?

Thanks.

**Comment by allenhwkim** [comment]
@polaris327 please make use of `value-formatter`, `display-property-name` as you can see in README.md

https://github.com/ng2-ui/auto-complete/blob/b49fee9fc0e2e7c08a14dfe146ef93cf7b0efc52/src/auto-complete.directive.ts#L213

**Comment by polaris327** [comment]
Thank you for your suggestion @allenhwkim 
Tbh, I am quite new to Angular 2 so it's a bit challenge for me. I have tried to figure it out as your guide but still no luck. 
Can you please update Plunker example so that I can understand exactly?
Sorry for bothering and thank you again. 

Regards.

**Comment by allenhwkim** [comment]
Here we go, http://plnkr.co/edit/uIvi2s?p=preview

**Comment by polaris327** [comment]
@allenhwkim Thanks for your quick reply. 
But it doesn't still seem to work properly. :(
For example, if you type a word(let's say "New York") in the search box, it lists "New York" correctly.
But if you select it, it's changed to "undefined"(It should be "New York")
This is the exact problem that I have been trying to solve so far. 
Can you still help me with this?

Many thanks!

**Comment by allenhwkim** [comment]
sorry my mistake. Updated with value-formatter.
http://plnkr.co/edit/uIvi2s?p=preview

**Comment by polaris327** [comment]
WOW! It works! I really appreciate you! @allenhwkim 
Great job!
