### ISSUE TITLE
Feature Request : Mobile

### ISSUE THREAD

**Issue by luckyboy07** [ng2-ui/auto-complete#180]
this component doesn't support mobile. i'd tried to used this but can't select selected item in dropdown.

**Comment by allenhwkim** [comment]
@luckyboy07 what's happening on mobile? can you take some screenshots?

**Comment by luckyboy07** [comment]
i used ionic 2 for this component.. there's no error  but the only problem was, it didn't support tap event, every time i scroll down the list the dropdown will closed and also cannot select i can only select by clicking enter or return in keypad. i can't provide you a screenshot coz there's no error on this component. thanks.. best regards..

**Comment by allenhwkim** [comment]
@ndcunningham can you take this by copying the technique used by` @ngui/datetime-picker `?

**Comment by houris** [comment]
Same problem here , Has anybody found a fix yet?

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
