### ISSUE TITLE
Not accept user input but not required

### ISSUE THREAD

**Issue by leonardosigrist** [ng2-ui/auto-complete#184]
**Steps to reproduce**

- In the plunker example: http://plnkr.co/edit/veDgkX?p=preview
- Click on the input
- Select an existent option from the list
- Now, clear the input content
- Remove the focus from the control

**Current behavior**

  - This control is not required but I can't leave it empty

**Expected behavior**

  - The input should be empty

**Aditional Information**

- The control cannot accept a value that don't exists on the list

**Comment by allenhwkim** [comment]
please use ` [accept-user-input]="true"` or  remove that line

**Comment by leonardosigrist** [comment]
But, if I use `[accept-user-input]="true"` the user will be able to type anything that not matchs with the content listed and if I use `readonly=readonly` the user loses the possibility to type on the control.
Is there any alternative to meet the scenario that the user can leave the input empty but cannot type something that not exists on the list?

**Comment by allenhwkim** [comment]
You may make use of this.

blank-option-text, string, guide text to allow empty value to be selected as in empty value of option tag.

**Comment by leonardosigrist** [comment]
I inserted the `blank-option-text="Select..."` in the followinig example: http://plnkr.co/edit/veDgkX?p=preview
The option "Select..." appears on the list, but after I choose another option, I can't  select the "Select..." option and, if I try to clear the content, it returns to the previous selected value.

**Comment by allenhwkim** [comment]
Yes, if `blank-option-text` and `[accept-user-input]="false"`, that's expected behaviour because blank option and accept user input contradicts each other. I recommend remove accept-user-input and add readonly=readonly
