### ISSUE TITLE
How to disable "No result Found"?

### ISSUE THREAD

**Issue by swapsword** [ng2-ui/auto-complete#186]
Hello Developers,

# How to disable "No result Found" in dropdown?

Problem: I have change the value of "No result found to "empty/space" by setting no-match-found-text to space. However, the dropdown for "No reult Found" is still there if you see closely. How can i disable/hide it completely, when result is not found?

Example:
[http://plnkr.co/edit/2qDToO?p=preview](url)

Regards,
Swapnil

**Comment by allenhwkim** [comment]
@swapsword thanks for reporting this.
You can achieve this by overriding css.

**Comment by allenhwkim** [comment]
```
    <style>
      ngui-auto-complete .no-match-found {display: none};
    </style>
```

**Comment by allenhwkim** [comment]
I may use this opportunity not to display any when `no-match-found-text` is false or blank.
* undefined -> 'No Match Found'
* false -> do not display dropdown
* blank -> do not display dropdown
* any text -> do display as given

**Comment by Atkinson88** [comment]
Setting the CSS doesn't seem to work

`<div auto-complete 
      [source]="arrayOfStrings"
      (valueChanged)="valueChanged($event)"
      placeholder="enter text" >
      <input [ngModel]="model1" />
    </div>

<style>
      auto-complete .no-match-found {display: none !IMPORTANT};
</style>`

Also tried what you suggested. 

`<style>
      ngui-auto-complete .no-match-found {display: none};
    </style>`

**Comment by antoinebeland** [comment]
The CSS solution seems to work only when we specify the keyword deep before the selector. For example:
```
/deep/ .no-match-found {
  display: none !important;
}
```
This solution works perfectly for me.

**Comment by krishna139** [comment]
Hi @antoinebeland ,

This solution is not working properly for me.
Please can you provide another solution if you know.

Any help will be admire.

Thank you.

**Comment by nguyendt214** [comment]
```
.ngui-auto-complete li.no-match-found{
    display: none !important;
  }

```
or you can create class cover everything like `hide-empty-search` for example
Then
```
:host /deep/ .hide-empty-search {
  .ngui-auto-complete li.no-match-found{
    display: none !important;
  }
}
```

**Comment by DarkAiR** [comment]
Even "No result found" dosnt show, a dropdown is shown and look like 2 pixels line.
I think this question about this problem also.

**Comment by igortobert** [comment]
2px line on ul :c

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
