### ISSUE TITLE
Dragging scrollbar (a result of content overflow)  in Internet explorer results in blur event, thus hiding the list of values

### ISSUE THREAD

**Issue by branislav-kurajda** [ng2-ui/auto-complete#187]
Have a fixed height list of values, as achieved by the following css

.ngui-auto-complete ul {
    max-height: 200px;
    overflow-y: auto;
}

**Current behavior**

When interacting with the scrollbar introduced by this css **in Internet Explorer a blur event is fired**, 
which results in the hiding of the list. Dragging a scrollbar in other browsers (Firefox, chrome) does not fire a blur event and thus these browsers are not affected.

**Expected/desired behavior**

List of values stays open during interaction with the scrollbar. 

**Other information**

This issue with Internet explorer is discussed here: http://stackoverflow.com/questions/2023779/clicking-on-a-divs-scroll-bar-fires-the-blur-event-in-ie

One can distinguish this particular blur event by the fact that it is not accompanied by a click event (as discussed in the link above). A workaround is thus possible, which only handles blur event after a click event was recieved.

**Comment by pravinrahurkar-tudip** [comment]
Hi,
I am using ng2-suto-complete module for that facing same issue on IE browser.
The merged solution is not working for me.

Any help for this is appreciated.

**Comment by branislav-kurajda** [comment]
Hello!

sorry I am no longer part of a project which needed the fix so am unable to
simulate it again. The fix worked for me though ...

Best,
bk.

**Comment by pravinrahurkar-tudip** [comment]
> Hi,
I am using ng2-auto-complete module for that facing same issue on IE browser.
The merged solution is not working for me.
Any help for this is appreciated.

Any update here...

**Comment by sooraj-zixent** [comment]
This solution works for me, May not be much efficient but working perfectly for me. 

Add this condition to prevent `this.hideAutoCompleteDropdown()` function in auto-complete.directive.js

```
this.hideAutoCompleteDropdown = function (event) {
            // Work around for closing of dropdown while scrolling
            if ($(".ngui-auto-complete:hover").length !== 0 && $(".ngui-auto-complete ul:hover").length === 0) {
                return;
            }
...
...
```

**Comment by CaffGeek** [comment]
I'm having this issue in Chrome.

**Comment by danail-vasilev** [comment]
Hi Guys.
We are having this issue in Chrome as well ! Could you please assist for a workaround and / or fix ?
Regards,

**Comment by PrasanthJayaraman** [comment]
I'm facing same issue in Chrome as well..

**Comment by Liad-n** [comment]
is there any workaround for that? i'm using version 0.12.0

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
