### ISSUE TITLE
Reset autocomplete input on select

### ISSUE THREAD

**Issue by ldoloscan** [ng2-ui/auto-complete#191]
Hello,
I'm wondering, is it possible to clear autocomplete input on select/change ?

I have tried to attach to this input `formControl` and then reset it `this.controlForm.reset()`, but this didn't worked.

It would be cool to get this done.

Thanks.

**Comment by dhanish2k** [comment]
Have you tried this.controlform.textcontrol.setValues('') where textcontrol is the name of your input box..?

**Comment by ldoloscan** [comment]
Yeah...no chances to get this done, I have even tried to update view with `ChangeDetectorRef.detectChanges()` and guess what...still nothing.

**Comment by allenhwkim** [comment]
Have you tried `blank-option-text` from README.md?

![image](https://cloud.githubusercontent.com/assets/1437734/25398260/543f82d2-29b9-11e7-8a2e-a4f6ee9eb899.png)

**Comment by ldoloscan** [comment]
Nope, not working, this blank-option-text is just appended to list but when i choose something from the list, on change i reset ngModel but selected option remains the same.

I don't have any other ideas how to reset input.

**Comment by allenhwkim** [comment]
`is it possible to clear autocomplete input on select/change`?

as far as i know `blank-option-text` should work, Please provide a plunker example if you need to investigate further.

**Comment by ldoloscan** [comment]
Yeah, there was a problem with package version, I've been used an old version 0.8.9, I've upgraded to latest version and everything works fine!!
The issue can be closed!

Thanks!
