### ISSUE TITLE
when min chars is set , even when no text is entered data is not shown in drop down 

### ISSUE THREAD

**Issue by AngularTx** [ng2-ui/auto-complete#193]
Hi,

If we are not using the min chars attribute , and if the user deletes the entered text , we will see the complete data below. This is fine..

But when we add min chars attribute and if everything is deleted , no drop down is shown. Is there a way that we can show the values. Becuase I am looking for a scenario where the initial data will be present and if the user enters something in the text box then the filtration will kick ..

I need the setting where user needs to enter 3 chars..

**Comment by allenhwkim** [comment]
You can use Observable source to make custom dropdown without using `min-chars`.

**Comment by AngularTx** [comment]
Hi, thanks for the reply. Do you have some template or sample code for this?

**Comment by allenhwkim** [comment]
You can find an example from README.md'
![image](https://cloud.githubusercontent.com/assets/1437734/25559066/bc622b30-2d01-11e7-88bf-a8f51b42e08e.png)

**Comment by AngularTx** [comment]
Thanks for the reply.

I have done some test with the example that is shown. 

I see one issue ...

Scenario 1 : 
1. Before even entering the data in the text box, i will have the data present which will be shown and then user can perform the selection either from drop down directly or via filtering. 
This is fine.

Scenario 2: 
1. Suppose i dont have the initial drop down filled . Technically the drop down is empty . 
When i focus on the text box, i see the message "No record Found" . This is something which the user would not expect .  Can i handle this in a different way ?

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
