### ISSUE TITLE
pre-selected object is translated to string

### ISSUE THREAD

**Issue by profanis** [ng2-ui/auto-complete#195]
If an input of a reactive form has a pre-selected object, this object is converted into a string with value the "display-property-name" property.

**example**
 ```
public continents = [{ id: 1, name: 'Asia',  population: '4,157,300,000'  } ];

  ngOnInit() {
    this.myForm = this.builder.group({
      continent : new FormControl(this.continents[0])
    })
  }
```
On page load, the property **continent** will have the value "Asia" instead of the object.
if however you select an item from the autocomplete list, the selected item will be an object (which is correct behavior)

An example is depicted on this plunkr
http://plnkr.co/edit/EvGDNkztfj3Xa4SNzD3i?p=preview

Do I miss something? Is there a way to overcome this issue?

Thanks

**Comment by allenhwkim** [comment]
By some reason, it is to set the initial value as `display-property-name`.
https://github.com/ng2-ui/auto-complete/blob/master/src/auto-complete.directive.ts#L94

@ndcunningham can you take a look at this to verify it is the right behaviour?

**Comment by profanis** [comment]
Is eventually the current behavior the expected one?

**Comment by will093** [comment]
I am also having the same issue. The behaviour seems odd - surely the selected item should always be the object and not the value of `display-property-name`.

**Comment by allenhwkim** [comment]
ping @ndcunningham

**Comment by andredatsch** [comment]
Same problem here, anyone know if it was fixed?

**Comment by sandrose48** [comment]
i have been stuck with this issue for months. Please fix it as soon as possible :'(

**Comment by ndcunningham** [comment]
@allenhwkim hey been thoroughly busy over the past couple of months. I will try and take a look at this it does not seem like it's the correct behaviour since selecting items in the list project the object.

**Comment by andredatsch** [comment]
@ndcunningham Nice one, any idea when we will got the official update?
