### ISSUE TITLE
Detect selection of auto-complete item. 

### ISSUE THREAD

**Issue by Pinank** [ng2-ui/auto-complete#196]
I need to perform some navigation action on selection of auto-complete item. Tried with the following code

```
autoCompleteListFormatter = (data:): SafeHtml => {
    let html = `<div (click)='clickComplete(data)'>${data.number} - ${data.name}</div>`;
    return this._sanitizer.bypassSecurityTrustHtml(html);
  }
```

it's passing the click method on searching than on click. 

Can anybody help me with this.

**Comment by smitthakkar96** [comment]
I don't think there is any way to achieve, the issue definitely deserves a PR but a quick fix would be to use something like this ``` (focusout)="addTextField(strategy.strategy, i)" ``` .
