### ISSUE TITLE
Perform 'start-with' instead of 'contains' search

### ISSUE THREAD

**Issue by ancabica** [ng2-ui/auto-complete#197]
Hello,

Is there a way of filtering the suggestion list using 'start-with' the characters the user just entered instead of 'contains'?

For example, in your continent example, I would like to write 'a' and only the continents starting with 'a' to be displayed in the selection list. In this case 'North America' would not remain an option in the list.

Thank you,
Anca

**Comment by allenhwkim** [comment]
Please use `Observable` source for customized search.

**Comment by smitthakkar96** [comment]
I didn't quite get what are you trying to convey, if I am not wrong there is no way to simply say call this function when someone performs the search if there is then it is not documented properly.
