### ISSUE TITLE
How to change source on user input (listen to user input changes)

### ISSUE THREAD

**Issue by ishehata** [ng2-ui/auto-complete#201]
**Current behavior**

  -  i am consuming api with paginated data, it only sends 20 items per page
  - when i enter a value in the auto-complete input, i couldn't find the needed item because it's not in the first 20

**Expected/desired behavior**

  - i need to make a new api call on user input to fetch more data from the api, so i guess i need some event to detect when input changes, i tried to use 
```
(change)="inputChanged($event)"
```
on the input tag, but it didn't work.

**Comment by emostafa** [comment]
i missed it in the documentation, its valueChange or ngModelChange.

thanks.

**Comment by emostafa** [comment]
i was mistaken, valueChanged and ngModelChange only occurs when user selected an item.

**Comment by d4viddur4ngo** [comment]
Hi emostafa, were you able to solve this issue. I happen to have the same scenario and no able to do it yet.

**Comment by emostafa** [comment]
@d4viddur4ngo unfortunately not yet. maybe i can work on writing a PR for fixing it in the weekend.

**Comment by allenhwkim** [comment]
There is `Observer` source.  You can make use of this.

**Comment by antajo** [comment]
I went with  Keyboard events 
(keyup)="onInputChangedEvent($event)"

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
