### ISSUE TITLE
Passing params to the source function

### ISSUE THREAD

**Issue by adeelmahmood** [ng2-ui/auto-complete#205]
Is it possible to pass parameters to the source function? I am using the autocomplete on a text box inside a grid component and different results should be retrieved based on which input box the search is being done for. In reactive forms, this is how I am specifying the source function:

`[source]="searchUdaValues.bind(this)"`

Instead, if I can pass params like this:

`[source]="searchUdaValues.bind(this, indexOfInput)"`

then I should be able to include the relevant information in the remote call to retrieve appropriate results.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
