### ISSUE TITLE
Selected dropdown value overlays with html placeholder

### ISSUE THREAD

**Issue by rakeshadak137** [ng2-ui/auto-complete#206]
![screenshot from 2017-05-06 11 02 40](https://cloud.githubusercontent.com/assets/10095146/25934664/dc90f032-363c-11e7-8074-19e970f19d3a.png)
If we directly select a value from drop-down (without typing anything), The value overlays with the input fields html placeholder. The placeholder and the selected values are displayed mixed giving an weired view. The same issue happens when we set a default value at init time in the drop-down.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
