### ISSUE TITLE
Multiple selection

### ISSUE THREAD

**Issue by amitgaur208** [ng2-ui/auto-complete#212]
**IMPORTANT**
_Please be specific with an example. An issue with_ **no example may be closed**.

**Steps to reproduce and a minimal demo**

  - _What steps should we try in your demo to see the problem?_
  - _Plunker example(REQUIRED)_
  - _If you cannot reproduce an issue with a plunker example, it's your environmental issue_

**Current behavior**
not able to select multiple options comma separeted
  - 

**Expected/desired behavior**
i need to add this like https://jqueryui.com/autocomplete/#multiple-remote
  - 

**Other information**

  -

**Comment by crh225** [comment]
https://rawgit.com/ng2-ui/auto-complete/master/app/index.html#/component-test
