### ISSUE TITLE
Not able to get textbox value as string

### ISSUE THREAD

**Issue by amitgaur208** [ng2-ui/auto-complete#213]
**IMPORTANT**
_Please be specific with an example. An issue with_ **no example may be closed**.

**Steps to reproduce and a minimal demo**

  - _What steps should we try in your demo to see the problem?_
  - _Plunker example(REQUIRED)_
  - _If you cannot reproduce an issue with a plunker example, it's your environmental issue_

**Current behavior**
I used reference variable for the text field but not able to get value using this
console.log(this.autocomplete.nativeElement.value);
  - 

**Expected/desired behavior**
I should be able to get value of text box as i can get other attributes of text box
  - 

**Other information**

  -

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
