### ISSUE TITLE
Update source change on user input

### ISSUE THREAD

**Issue by gundawarprasad** [ng2-ui/auto-complete#214]
Hi,
Currently I am using ng2-auto-complete.But I found couple of issues.
i).When I try to get the updated source based on user input,dont have any attributes in ng2-auto-complete component.So I have used (keyUp) event.But again the source is not updating,which required an event like focus.We are having couple of issues with dynamically triggering focus event upon getting source values.
ii)Everytime it is displaying "No Result Found." Eventhough after autocomplete selection.
iii)Backspace is not updating the source values.

Can anyone please address above issues.
Thanks in advance.

**Comment by GeorgeSokolovsky** [comment]
It will be great, if you'll create a plunker or something like this. So I'll better understand what you are trying to achieve.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
