### ISSUE TITLE
"starts with" matches should be on top of the filtered options

### ISSUE THREAD

**Issue by BarnT** [ng2-ui/auto-complete#215]
When user enters text into the input field, the filtered list should 
    - first show the options which "starts with" the typed text
    - followed by all the other ("contains") matches

**Steps to reproduce and a minimal demo**

  -  Use the following Plunker example: http://plnkr.co/edit/ztpZ3gFI5YhqZ5sALlHI?p=preview
  -  Type 'is' into input field! 

**Current behavior**

  - The order of the filtered options' list is: 'this', 'is', 'list' 

**Expected/desired behavior**

  - The order of the filtered options' list should be: 'is', 'this', 'list'

**Other information**

  - Maybe this behavior could be able to be set by an attribute

**Comment by HoosierWrangler** [comment]
We need the same thing, we are probably going to have to fork this and republish quickly as we need this ASAP. It's a 10 minute change but know the author(s) probably have their hands full

**Comment by abojar** [comment]
@HoosierWrangler Why don't you issue a pull request if you already know how to 'fix' it and how long it takes to fix it? I'm also looking froward to that feature.

**Comment by sudreg** [comment]
Hi, 
Is this feature implemented yet ?  
If not, please provide some hints on if i can do some workaround/customization on my own. 

I'm in desperate need of this feature.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
