### ISSUE TITLE
Set a ngModel to autocomplete

### ISSUE THREAD

**Issue by elioth010** [ng2-ui/auto-complete#216]
**IMPORTANT**
_Please be specific with an example. An issue with_ **no example may be closed**.

**Steps to reproduce and a minimal demo**

  - _What steps should we try in your demo to see the problem?_
  - _Plunker example(REQUIRED)_
  - _If you cannot reproduce an issue with a plunker example, it's your environmental issue_

**Current behavior**
  - 
when i set the ngmodel programatically, i get [object Object],
but when i select normal flow show wells

**Expected/desired behavior**
i want set the ngModel with a service response and set de default value
and view well
![image](https://cloud.githubusercontent.com/assets/5650869/26385817/6d094bf2-3fff-11e7-83ee-9803c854e059.png)

  - 

**Other information**
There is an example
http://plnkr.co/edit/dbzofOYTom4nh5I2kw8B?p=preview
  -

**Comment by FiratOZ** [comment]
I have the same problem, is there a way to solve this issue?

**Comment by GeorgeSokolovsky** [comment]
I've created a PR to resolve this issue, you can check it out. https://github.com/ng2-ui/auto-complete/pull/221

**Comment by ndcunningham** [comment]
can this be closed?

**Comment by elioth010** [comment]
Yes, sure
