### ISSUE TITLE
where i need to put ng2-autocomplete folder in my project

### ISSUE THREAD

**Issue by vanilkumar** [ng2-ui/auto-complete#219]
**IMPORTANT**
I am trying to use auto complete feature in my project but after down loading the package,
when ever i import it to my project is it displaying error folder not find.

so please help me in this

PHNO : 8884099799

**Comment by GeorgeSokolovsky** [comment]
Can you share your project structure and build tool config?

**Comment by smitthakkar96** [comment]
use npm
