### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by crh225** [ng2-ui/auto-complete#220]
How can we do multi select?

**Comment by allenhwkim** [comment]
Pirate use as a component for multi select

https://rawgit.com/ng2-ui/auto-complete/master/app/index.html#/component-test

**Comment by swapsword** [comment]
Can you please create a plunker for above multi-select demo? That will be helpful.

**Comment by evasquez26** [comment]
@swapsword It might be too late, but just check the source code of this same project, the provided example it is right here https://github.com/ng2-ui/auto-complete/blob/master/app/component-test.component.ts :)
