### ISSUE TITLE
valuechanged event does not work (even on your demo)

### ISSUE THREAD

**Issue by HoosierWrangler** [ng2-ui/auto-complete#222]
See http://plnkr.co/edit/3pB1Gx?p=preview and look at the console as your instructions say, totally blank, we're going to have to switch controls, uggh, like this one too.

**Comment by allenhwkim** [comment]
`valueChanged` is only get fired when you selected from list.

![image](https://user-images.githubusercontent.com/1437734/26948860-e0d167be-4c65-11e7-9768-01d0677bbba3.png)
