### ISSUE TITLE
How to enable matched text highlighted?

### ISSUE THREAD

**Issue by uiravi** [ng2-ui/auto-complete#223]
Hi i  have implemented this. but trying to enable matched text highlighted. if there any option. please suggest. Thanks :)

**Comment by allenhwkim** [comment]
there is no  such a feature at this moment.

**Comment by uiravi** [comment]
Thanks 👍  if possible please implement.

**Comment by smitthakkar96** [comment]
It's a good feature request @allenhwkim why don't we mark it as a feature request

**Comment by allenhwkim** [comment]
@smitthakkar96 it's a good feature. However, I am not sure of the size, complexity, and performance of code for this implementation as a basic feature.

This can be done using `list-formatter` already. 

I am not sure that this module should provide this custom list-formatter.

We still can build an example how to highlight it on the list though.

**Comment by beeing** [comment]
Just a suggestion, this is a good match for autocomplete - https://github.com/farzher/fuzzysort
and also have highlight feature

**Comment by allenhwkim** [comment]
You still can complete with `list-formatter`. This is an example. http://plnkr.co/edit/4ekcPC?p=preview
