### ISSUE TITLE
Demo plunkers don't work

### ISSUE THREAD

**Issue by ArnaudPel** [ng2-ui/auto-complete#224]
**Steps to reproduce and a minimal demo**
  - Open a plunker example from the npm page https://www.npmjs.com/package/ng2-auto-complete.
    (eg. http://plnkr.co/edit/WfgdcHLc8KDvsI2G2tHw?p=preview)

**Current behavior**

  - The plunker fails to load.

**Expected/desired behavior**

  - The plunker works, so that I can submit the issue I originally wanted to :)

**Other information**

  - It seems to be an rxjs import issue:` Error loading http://run.plnkr.co/Ybwf1Ht6qBnRWJqM/tslib as "tslib" from https://unpkg.com/rxjs/Subject.js`

**Comment by tokuduz** [comment]
Hello,

I got no issues with loading plunker. For me it is working normally.

TK

**Comment by GeorgeSokolovsky** [comment]
For me, it's also working as expected.

**Comment by ArnaudPel** [comment]
Hum, ok just tried at home, it does load fine. I'll have another go at work tomorrow and close the issue. Thanks

**Comment by ArnaudPel** [comment]
Also fine at work, may have been a temporary hiccup on plunker side then. Sorry for the noise.
