### ISSUE TITLE
Unresponsive Results

### ISSUE THREAD

**Issue by shariqs** [ng2-ui/auto-complete#225]
I'm using a YouTube autocomplete API to emulate the YouTube autocomplete searchbar. 

**Current behavior**

Currently, when I type in some characters, the auto-complete module displays the right results. But when I press enter, the query goes to the first result in the autocomplete array instead of what the user types in. 

If I quickly delete everything in the search-bar and type something else in, it still goes to the first result in the array.

Example:
I type in "That's what I like" and quickly delete it and type "Bruno" and press enter, the form will submit "That's what I like" even though the bar displays "Bruno"
 
![captured2](https://user-images.githubusercontent.com/15084721/27311846-b345f132-5518-11e7-94da-d02bfb2fd02f.PNG)

**Expected/desired behavior**
When user presses enter, the information that the user has typed should be submitted. When the user presses the down button or clicks on something, then the value that has been selected should replace the text in the box.
  -

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
