### ISSUE TITLE
Data not binding when coming from backend 

### ISSUE THREAD

**Issue by AmitAKB** [ng2-ui/auto-complete#226]
**IMPORTANT**
html file
```
 <input ngui-auto-complete
                                  formControlName="continent"
                                  [source]="continents"
                                  [path-to-data]="fName"
                                  [list-formatter]="autocompleListFormatter"
                                  value-property-name="id"
                                  display-property-name="name"
                                  placeholder="Contients"
                                  (ngModel)="fName"
                                  (valueChanged)="valueChanged($event)"
                                  class="form-control">
```

main.ts file
```
//firstname autocomplete function
   firstNameListFormatter = (data: any) => {
     let html = `<span>${data.firstName}</span>`;
     return this._sanitizer.bypassSecurityTrustHtml(html);
   }

   //firstname value changed
   fnameChange(value:any){
     if(value.length>2){
       this._artistService
           .getArtist('firstname='+value+'&lod=MAX')
           .subscribe( Response => {
               this.fName.splice(0,this.fName.length);
               this.fName.push(value.content[0]);
             },
            resFileError => this.errorMsg = resFileError);
      }
   }
```

services.js
```
getArtist(body: Object){
    return this._http.get(this._url+"/artists?"+body)
           .map( (response: Response) =>{
              if(response.status < 200 || response.status >= 300) {
                throw new Error('This request has failed ' + response.status)
              } else {
               return response.json();
              }
            })
           .catch(this._errorHandler);
  }
```
**Current behavior**
It is not showing data coming from backend, when click on outside the input box and go back to select the current input box then data display.

**Expected/desired behavior**
When I change value in input box call ajax request (it working fine data coming from backend) and this backend data replace with new data and display on view mode.

**Comment by BuriakPavel** [comment]
Try to change [source] attribut to 'fName' or set data from backend to the 'continents' object when component init (at ngOnInit() method)

**Comment by AmitAKB** [comment]
I'm tried this things but last record not push in source attribute.
when i click on outside the input box and again click on input box then result showing.
It is not properly bind. 
Otherwise give the trigger event for when data change.

**Comment by marslan390** [comment]
Same issue is coming here.

**Comment by marslan390** [comment]
@AmitAKB any progress?

**Comment by AmitAKB** [comment]
@marslan390 No, It is showing same problem.
Have you find any solutions for this.

**Comment by erijin** [comment]
@AmitAKB can u share it in plunkr

**Comment by AmitAKB** [comment]
https://plnkr.co/edit/zmsUE6MifTO9tMW972VJ?p=preview

OR 
http://plnkr.co/edit/2XRrck2cWVWcvbJnj6z5?p=preview 

This plnkr replace the below code in app/app.component.ts
Code:
import { Component, OnInit } from "@angular/core";
import { DomSanitizer, SafeHtml } from "@angular/platform-browser";
import { FormGroup, FormControl, FormBuilder, FormArray, Validators } from '@angular/forms';

@Component({
  selector: "my-app",
  template: `
  {{myForm.value | json }}
   <form class="form-horizontal" [formGroup]="myForm" (ngSubmit)="onSubmit(myForm.value)">
    <div>
        <div class="col-sm-5">
            <input  ng2-auto-complete
                   formControlName="continent"
                   [source]="continents"
                   [list-formatter]="autocompleListFormatter"
                   value-property-name="id"
                   display-property-name="name"
                   placeholder="Contients"
                   (ngModelChange)="onChangeValue($event)"
                   class="form-control">
        </div><br/>
        <button type="submit">Submit</button>
    </div>
</form>
 `
})
export class AppComponent implements OnInit{
 
     public continents = [{
      id: 1,
      name: 'Asia',
      population: '4,157,300,000'
    }, {
      id: 2,
      name: 'Africa',
      population: '1,030,400,000'
    }, {
      id: 3,
      name: 'Europe',
      population: '738,600, 000'
    }, {
      id: 4,
      name: 'North America',
      population: '461,114,000'
    }, {
      id: 5,
      name: 'South America',
      population: '390,700,000'
    }, {
      id: 6,
      name: 'Australia',
      population: '36,700,000'
    }, {
      id: 7,
      name: 'Antartica',
      population: 0
    }
    ];
  public myForm: FormGroup;
  constructor(private builder: FormBuilder, private _sanitizer: DomSanitizer) {  }
  ngOnInit() {
    this.myForm = this.builder.group({
      continent : "",
    })
  }
  autocompleListFormatter = (data: any) : SafeHtml => {
    let html = `<span>${data.name}</span>`;
    return this._sanitizer.bypassSecurityTrustHtml(html);
  }
  onChangeValue(){
    this.continents = [{
      id: 10,
      name: 'Test',
      population: '2,157,300,000'
    }, {
      id: 11,
      name: 'Testing',
      population: '2,030,400,000'
    }];
  }
  onSubmit(value:any){
    console.log(value);
  }
}

When I entering the "test" string it is not display in drop-down list, but when click on outside the drop-down and again click on drop-down list then latest data updated.
Please check and let me know about this?

**Comment by pawelchmara** [comment]
I have the same problem. When new list of items is received from service and auto complete list is visible then auto complete is not updated.

I think that auto complete should provide a method to force the refresh of the list of items.

**Comment by allenhwkim** [comment]
If the source is dynamic, the source should be an Observable one. Please take a look into Observable example.

**Comment by pawelchmara** [comment]
Thanks for help. It works fine.
