### ISSUE TITLE
how to disable or make readonly ng2-auto-complete

### ISSUE THREAD

**Issue by krishna139** [ng2-ui/auto-complete#227]
**IMPORTANT**
_Please be specific with an example. An issue with_ **no example may be closed**.

**Steps to reproduce and a minimal demo**

  - _What steps should we try in your demo to see the problem?_
  - _Plunker example(REQUIRED)_
  - _If you cannot reproduce an issue with a plunker example, it's your environmental issue_

**Current behavior**

  - 

**Expected/desired behavior**

  - 

**Other information**

  -

**Comment by bushybuffalo** [comment]
@krishna139 you can disable it simply by setting [disabled] property like so:
```
<input auto-complete [disabled]="myCondition" />
```

You can do the same thing with [readonly], but it will not prevent the list from displaying on click.

@allenhwkim it would be nice to have a way to disable the list when in readonly mode. 
I know it is currently a feature to keep the list in readonly mode to enable choosing a value without allowing a manual input.
In my case, I would like to set readonly mode to keep the value in my form (as disabled state removes the input from form values), but stop showing the list to prevent the user from changing the value. Or is there something I missed ?

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
