### ISSUE TITLE
TAB out of field doesn't remove "No Results Found" box when using accept-user-input="true"

### ISSUE THREAD

**Issue by donsutherland** [ng2-ui/auto-complete#231]
When using autocomplete with accept-user-input="true", when I TAB out of the field to the next field with a value not on the list, the autocomplete box remains displaying the "No Results Found" until the screen is clicked.

**Steps to recreate:**

1) Click plnkr url below.
http://plnkr.co/edit/FWk0LLgybDmyigPWfzry?p=preview

2) Enter a text value not present on the list

3) Observe that the "No Results Found" is still present over the Value display.     If you click the screen the "No Results Found" box is removed.

**Expected**

That the box would be removed when the box loses focus.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
