### ISSUE TITLE
[Safari on iOS] Autocomplete dropdown is not closed when click outside of dropdown area

### ISSUE THREAD

**Issue by thanhpd** [ng2-ui/auto-complete#232]
**Steps to reproduce and a minimal demo**
- Open the autocomplete dropdown on Safari on iOS
- Tap on outside area to close it
Plunker example: Any demo example of this repo can be used to reproduce the issue.
http://plnkr.co/edit/3pB1Gx?p=preview

**Current behavior**
- The dropdown did not close. In Chrome for Android and desktop browsers, it was able to close.

**Expected/desired behavior**
- The dropdown can be closed successfully

**Other information**
- Device: iPad mini 2 - iOS 10.3.2

Any help is appreciated, thank you.

**Comment by alainjb** [comment]
I have encountered the same issue with Safari on iOS.  Also when you select an item on drop down it gets highlighted but selection does not register and drop does not go away.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
