### ISSUE TITLE
Auto complete - shows wrong values

### ISSUE THREAD

**Issue by KRav007** [ng2-ui/auto-complete#233]
<img width="229" alt="bildschirmfoto 2017-07-10 um 23 01 57" src="https://user-images.githubusercontent.com/2427915/28039905-283c5e98-65c4-11e7-8cbe-0644679c0657.png">

What kind of logic is used, to "filter" the list, if you insert values into the autocomplete?

**Current behavior**
See the screenshot, I fill in "aaaa" and the list contains "DUD1".
Why is "DUD1" shown? There is no "a" in this value?

**Comment by allenhwkim** [comment]
The default logic is `JSON.stringify(element).indexof('aaa')> 0`
If you don't like this logic, you can make your own Observable source to filter out.

If you need further assist, please create a plunker example to reproduce this issue.
