### ISSUE TITLE
Key binding for closing auto complete overlay

### ISSUE THREAD

**Issue by kyue1005** [ng2-ui/auto-complete#234]
**IMPORTANT**
As using the autocomplete for search keyword suggestion, user should be able to close the overlay to input their custom string for a better UX.

**Current behavior**

  - can only close overlay by clicking outside of the list

**Expected/desired behavior**

  - can close overlay by key, eg. ESC key

**Other information**

  -

**Comment by Fideon** [comment]
Also, is there a way of closing the overlay programmatically?

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
