### ISSUE TITLE
how can i set a scroll bar in the autocomplete list, when there is more data items to show.

### ISSUE THREAD

**Issue by experionakash** [ng2-ui/auto-complete#235]
**Steps to reproduce and a minimal demo**

  -   <input ng2-auto-complete 
formControlName="vehicleTypeId" 
[source]="vehicleTypes" 
[list-formatter]="myValueFormatter" 
[accept-user-input]="false"
[match-formatted]="true"  
(valueChanged)="vehicleTypeChanged($event)" 
value-property-name="id" 
display-property-name="name"
max-num-list="5"
class="form-control" maxlength="15">

**Current behavior**

  - now there is no scroll option when there are more items in the list.
  - while giving 'max-num-list="5" ' only 5 items are displayed.

**Expected/desired behavior**

  - Need a scroll bar while setting the property 'max-num-list="5"', and there are more than 5 items in the list.

**Other information**

  -

**Comment by allenhwkim** [comment]
Duplicate to https://github.com/ng2-ui/auto-complete/issues/199
