### ISSUE TITLE
Input show 'undefined' on open form

### ISSUE THREAD

**Issue by josecarlosweb** [ng2-ui/auto-complete#236]
Hello,

I try use on my form like this:
```
<input id="contato-primario" type="text" class="validate"
                   auto-complete [source]="fonteContatos" placeholder="Contato Primário" [ngModel]="conta.contatoPrimario"
                   [list-formatter]="formatterListContato" display-property-name="nome"  (valueChanged)="valueChanged($event)"
                   value="{{conta.contatoPrimario.nome}}" name="contatoPrimario">
```

On start the form, the input show "undefined" or when it's empty. I tried to change the value of the attribute to empty, but it did not work.

I just need that input is clear on show empty form.

Sorry if not suitable place for ask here.

**Comment by taiducnguyen** [comment]
Hi Jose,

Try to use value-formatter and return a string value , this works for me
