### ISSUE TITLE
not giving whole object when we type whole word in text field

### ISSUE THREAD

**Issue by narsignt** [ng2-ui/auto-complete#239]
Hi all,
http://plnkr.co/edit/2osUq6?p=preview :  Here i typed "Antartica" and clicked submit button and  i got " {continent: "Antartica"}" this response but here i am expecting the response like 

continent: { 
                      id:7,
                      name: "Antartica",
                      population:0
                   }
Can anyone please address above issues.
Thanks in advance.

**Comment by allenhwkim** [comment]
I don't see any issues here.

![image](https://user-images.githubusercontent.com/1437734/28579505-daf7f24c-712a-11e7-9497-3c23764f1952.png)
