### ISSUE TITLE
Entered value is not accepted when press Enter

### ISSUE THREAD

**Issue by raviji** [ng2-ui/auto-complete#246]
Expectation:

- Ex: when typing "Bangalore" in the input box will have text "Bangalore" and in the auto suggest list will have few suggestion. Now if i press Enter then it goes `undefined` because it is always try to select the first value from the auto suggest list.

- When pressing Up/Down arrow keys in the keyboard then its navigating in the list only but in the input field value also would be as list, so that when press up/down key the first value of "Bangalore" will be selected and then second value from the list.

**Comment by almothafar** [comment]
is it related to #252 ?
