### ISSUE TITLE
Reactive forms plunkr is out of date

### ISSUE THREAD

**Issue by gsej** [ng2-ui/auto-complete#251]
The reactive forms plnkrs use the old value-property-name attribute instead of select-value-of. 

The first one is at http://plnkr.co/edit/2osUq6?p=preview.

I've forked and corrected it here: 

http://plnkr.co/edit/7kFmGK?p=preview

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
