### ISSUE TITLE
Hitting the enter key after focusing on the input and before entering any characters will display 'undefined'. 

### ISSUE THREAD

**Issue by jwoo896** [ng2-ui/auto-complete#252]
Everything works as it should really. The text in the input box becomes "undefined" when I hit enter without typing anything in. This specifically only happens when I hit enter right after focusing on the input box and before typing anything in at all. If I type something in first and then clear out what I typed in and hit enter on an empty string, nothing happens (which is what I want). 
![screen shot 2017-08-10 at 3 21 00 pm](https://user-images.githubusercontent.com/15336369/29187971-8c9bb1a8-7ddf-11e7-9137-b12544b00877.png)

**Comment by allenhwkim** [comment]
You can auto select the first item by having `                   [auto-select-first-item]="true"`

**Comment by jwoo896** [comment]
I actually don't want it to. I want it to recognize that nothing was entered, and then do nothing. I know that's a very nit-picky thing.. If it's more trouble than its worth I'll just leave it hahaha

**Comment by lemarsu** [comment]
When the Input `auto-select-first-item` is set to `false` (or not given), the behaviour is what @evasquez26 introduced with PR #240. When the `auto-select-first-item` is set to `true`, the behaviour should be the same as before PR #240.

Maybe @evasquez26 could have an idea ?

**Comment by evasquez26** [comment]
Yes I think I know what might be happening with the undefined value. I'll submit a PR later

**Comment by allenhwkim** [comment]
@evasquez26 thank you very much.

**Comment by jwoo896** [comment]
Thank you so much!
