### ISSUE TITLE
How to clean selected data?

### ISSUE THREAD

**Issue by vicabelotelova** [ng2-ui/auto-complete#256]
**# i have this input**
```
<div class="form-group col-md-6" >
           <input ngui-auto-complete
            [source]="RegionsArray"
            [max-num-list]="10"
            [list-formatter]="autocompleListFormatter"
            (valueChanged)="searchCitiesInBase($event)"
            value-property-name="OCATD"
            display-property-name="FullName"
            class="form-control"
           />
</div> 

```
**# How to clean selected data if i will change another ngui-auto-complete input**
**# And how i can paste my value from json to ngui-auto-complete input**
_i couldn't found some information about this_

**Comment by allenhwkim** [comment]
I do not fully understand your issue. Please create a plunker example and explain what you expect and what actually happening

**Comment by vicabelotelova** [comment]
@allenhwkim I would like to change the field "country" to clear the selected value in the field "city"
http://embed.plnkr.co/sG4bCHVdcKawJAZS5fNU/

**Comment by allenhwkim** [comment]
Please re-assign the value when the value is selected using  `valueChanged` or `ngModelChange`

`submit` is out of the scope.

**Comment by vicabelotelova** [comment]
@allenhwkim thank you it's working
