### ISSUE TITLE
Does not work with IE

### ISSUE THREAD

**Issue by JLEdward** [ng2-ui/auto-complete#257]
It appears that IE currently does not recognize a local array as the source and given out error: "Invalid type of source, must be a string. e.g. http://www.google.com?q=:my_keyword".
The statement "this.source.constructor.name" returns "undefined" for IE while another browser like Chrome would correctly identify an array.

**Comment by DashPriyabrata** [comment]
Encountered the same issue. @JLEdward Any resolve/work around for this issue? Is there another control available to complete the autocomplete job?
