### ISSUE TITLE
'Undefined' text in input text after tabbing

### ISSUE THREAD

**Issue by TomaszBorczyk** [ng2-ui/auto-complete#259]
When tabbing if nothing is selected/typed or just empty spaces typed, input value is displayed as 'undefined'; I'm using Angular 4 reactive forms.

Another similar issue: type something, select from list (or not), deselect the input (input value stays as it should), then select again without changing its value, then tab or enter - value changes to undefined.

Plunker from docs to reproduce (just select the input and tab, text will be displayed as undefined):
http://plnkr.co/edit/2osUq6?p=preview

I would like input to be blank if tabbed without typing anything/typing spaces. 
Is there any workaround? I tried using [accept-user-input]="false", but it disables blank input completely

**Comment by allenhwkim** [comment]
@evasquez26 can you take a look into it? Even with the recent release, this problem still exists.

**Comment by almothafar** [comment]
I got this issue here too, it is annoying, I want to use to keep the option for him to use from the auto-complete list or let him type anything a user wants.

**Comment by almothafar** [comment]
I used this fork:
`"@ngui/auto-complete": "github:galkinrost/auto-complete#ef931a7fa2aec095ca64155df2197a2432761711",`
And was very helpful to solve my issue.

**Comment by almothafar** [comment]
You may want to see my pull request #265 
You may also test my fork `"@ngui/auto-complete": "github:almothafar/auto-complete#0.14.2",`

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
