### ISSUE TITLE
how do i set z-index of list?

### ISSUE THREAD

**Issue by RawatPraveen** [ng2-ui/auto-complete#260]
I want to set z-index of the list which has z-index as 1 by default. How do i do it?

**Comment by pawelchmara** [comment]
You can add this to your css:

```
ngui-auto-complete {
  z-index: 100 !important;
}
```

**Comment by renanmoraes** [comment]
dont work for me :(

**Comment by RawatPraveen** [comment]
@pawelchmara are u sure that this worked for you as i have tried it and it didn't not worked.

**Comment by pawelchmara** [comment]
Yes, it works. Where are you put this css rule (in global stylesheet or in component stylesheet)? Maybe z-index value should be greater...

**Comment by RawatPraveen** [comment]
@pawelchmara i have added this css in my style.css file and there it did not worked. I will try wtih component css.

**Comment by allenhwkim** [comment]
@pawelchmara your css rule goes into your component with  encapsulation stragegy`encapsulation: ViewEncapsulation.None`, e.g. appComponent, parentComponent, etc.. e.g., http://plnkr.co/edit/3pB1Gx?p=preview

**Comment by RawatPraveen** [comment]
Its fixed with that trick. Thanks

**Comment by adamwe499** [comment]
You should install z-index direct to template . It's work fine.
<input class="form-control" auto-complete [source]="Aerodromes"  z-index="5" />
