### ISSUE TITLE
Can I make the field required?

### ISSUE THREAD

**Issue by vicabelotelova** [ng2-ui/auto-complete#261]
**I need make my field required
Like this**
`<input ngui-auto-complete
            [formControl]="RegionValue"
            [source]="RegionsArray"
            [list-formatter]="autocompleListFormatter"
            (valueChanged)="searchCitiesInBase($event)"
            display-property-name="FullName"
            class="form-control"
            required
            />`
**but this way it's not working**

**Comment by allenhwkim** [comment]
It seems out of scope. Please make a plunker example, and tell me what you expect and what you see.

**Comment by vicabelotelova** [comment]
@allenhwkim I want to make my input field will be required in my form

**Comment by vicabelotelova** [comment]
I fixed it
