### ISSUE TITLE
directive rtl support

### ISSUE THREAD

**Issue by anysite** [ng2-ui/auto-complete#263]
**Current behavior**

In directive, on rtl enviroment, the box is  out of place. The reason - style given to list is left:0;
Plunker: http://plnkr.co/edit/ajL968p8NQXJNEtbdGy6?p=preview

  - 

**Expected/desired behavior**

Make option to rtl box - would make right:0 instead of left:0;

  - 

**Other information**

If it's needed, I can fix it myself and make pull request, just want to know if there is a way to do it in current code

  -

**Comment by allenhwkim** [comment]
Thanks for reporting this. 
The stylesheet can be overwritten by user for this.
However, if there is a generic solution, a PR would be appreciated.

**Comment by anysite** [comment]
But this is not stylesheet. That's hard coded in js, and css hardly can override inline css

file: src/auto-complete.directive.ts
function: styleAutoCompleteDropdown

`
this.acDropdownEl.style.left = "0";
`

**Comment by allenhwkim** [comment]
@anysite sorry for misunderstanding, please make a PR for this

**Comment by anysite** [comment]
PR: #264 
Hope I sis it well, my first PR in github
