### ISSUE TITLE
Styling the list of options

### ISSUE THREAD

**Issue by renanmoraes** [ng2-ui/auto-complete#268]
**IMPORTANT**
_Please be specific with an example. An issue with_ **no example may be closed**.

**Steps to reproduce and a minimal demo**

  - _What steps should we try in your demo to see the problem?_
  - _Plunker example(REQUIRED)_
  - _If you cannot reproduce an issue with a plunker example, it's your environmental issue_

**Current behavior**
I am not able to apply any style to the list, I need to move it like for example zmenting the index as giving a float: left among others.

I think this is because this information is set to my tag.

**Expected/desired behavior**
In my expectation is that I can define the style I want the list of options.

**Other information**
I'm using materialize along with angular 2, and my input looks like this:

```
<div class="input-field col s12">
      <i class="material-icons prefix input-icon">map</i>
      <input ngui-auto-complete
               class="validate"
               type="text"
               materialize="autocomplete"
               id="autocomplete-state"
               placeholder="Informe seu estado"
               [(ngModel)]="selectedState"
               [source]="states"
               list-formatter="name"
               display-property-name="name"
               max-num-list="5"
               tab-to-select="true"
               auto-select-first-item="true"
               no-match-found-text="Nenhum estado com este nome"
        />
      </div>
```

This is the view I have when clicking on the input

![captura de tela de 2017-09-04 17-27-42](https://user-images.githubusercontent.com/12611706/30037972-73a72c48-9196-11e7-9628-efc2f4b3627a.png)

**Comment by balaganapathynt** [comment]
Try to change the inline css properties inside ng2-auto-complete>dist>ng2-auto-complete.directive file.
