### ISSUE TITLE
undefined issue on tab:

### ISSUE THREAD

**Issue by Pinank** [ng2-ui/auto-complete#269]
If we don't select any value from the list and press tab than it's going to set undefined in the textfield.

The issue is in plunker code also: [(http://plnkr.co/edit/A5CW2e?p=preview)]. 

Also on searching its not showing all the records and not having scroll in the autocomplete dropdown.

Is there any way to handle this?
![screen shot 2017-09-05 at 10 30 05 am](https://user-images.githubusercontent.com/3683505/30046057-92d4de0a-9225-11e7-8323-37686465e06d.png)

**Comment by pablogarciamiranda** [comment]
Same problem here.

**Comment by Pinank** [comment]
1 more thing to notice. I have to user autocomplete in grid. So there will be multiple dropdowns in my case.

I have dropdown of city, country & state and while searching values it should also pass the value of its parent dependant. So If i'm searching states then i have to pass the preselected country id inthat erticular row the search request. Now i'm unable to get the details of on which index the user is currently searching. Is there any way to pass one extra param while searching?

**Comment by narsipanta** [comment]
me also facing the same issue

**Comment by shubham-k7** [comment]
Unable to replicate in the Plunker provided by you. Can you expand a bit more?

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
