### ISSUE TITLE
How to set already saved value to auto-complete?

### ISSUE THREAD

**Issue by RawatPraveen** [ng2-ui/auto-complete#274]
I have implemented this control and using this i have saved some details. Now problem is how do i set back when user comes to edit a record. In this case whatever user have saved should be selected by default.

I have gone through documents but did not find any doc or link in which it is shown how to set a data back or what should be the best practice to save a data or set already saved data.

I haven't created any plunk before and this is my first plunk. Its not working at the moment but by going through it you will understand what i want to say.

[plunk](http://plnkr.co/edit/LGKdFnshohuiDy0FvS3n?p=preview)

**Comment by allenhwkim** [comment]
@RawatPraveen there is no such option to select or add your pre-selected values.
You can make use of `Observer` source by manually handling it.
