### ISSUE TITLE
No Data found is showing first time data binding

### ISSUE THREAD

**Issue by satishmnd** [ng2-ui/auto-complete#275]
No Data found is showing first time when i bind dynamic data. if click outside and if i type its working.

The issue is not exist for static data.The issue is not exist for static data.
![capture](https://user-images.githubusercontent.com/17784212/30485322-a2b828f4-9a4a-11e7-9cf0-3871cbf88a94.PNG)
![capture12](https://user-images.githubusercontent.com/17784212/30485323-a2c439d2-9a4a-11e7-89fc-3be61146c095.PNG)

problem i found is list formatter is hitting second time only

**Comment by allenhwkim** [comment]
Please create an workable example, e.g. plunker, jsfiddle to reproduce your issue. Without it, it will be closed.
