### ISSUE TITLE
accept-user-input=false does not work as expected

### ISSUE THREAD

**Issue by egesu** [ng2-ui/auto-complete#277]
**Current behavior**

  - I set `accept-user-input=false`, but when I continue typing, the last character after valid input is not deleted. I know I cannot explain it well, just see the plunker.

**Expected/desired behavior**

  - The value selected should not change.

**Other information**

  - In the plunker, select "Asia" from the list. Then click on the input and continue typing a few letters. Lose the focus from input. If you have written "Asiaandme", it should revert back to "Asia". However it becomes "Asiaa". The last character after valid input stays there. See the plunkr:
http://plnkr.co/edit/n4RddeYbdFJqUSri0FO7?p=preview

**Comment by diegogarciaa** [comment]
I am having this issue to. When user types for example: "asdasdas", the input should be set to initial stage when empty in the first place. Or be set to its initial value

**Comment by SlapBassist** [comment]
This is also not working properly for me.

**Comment by sh4ka** [comment]
It is not working, it seems that it somehow reverts to the last char stored in the control before a bad input is typed.
Steps:
1 .- Type As, select Asia.
2.- Type 'aaaaa' after 'Asia', you go back to Asia when focus is lost.
3.- Type 'bbbb' after 'Asia', you go back to 'Asiaa'.
4.- Type 'ccccc' After 'Asiaa', you go back to 'Asiab'.
And so on...

**Comment by nobady90** [comment]
in many situations this problem comes out ... sometimes it also accepts characters not in the list and keeps the first character in the field ... I think this is a big problem.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
