### ISSUE TITLE
It possible to add infinite scroll to dropdown list?

### ISSUE THREAD

**Issue by sergeyslonimsky** [ng2-ui/auto-complete#278]
I have more than a thousand values in my database. Can I get first several values on init, and when scroll down to bottom send a request to get other batch of values.

**Current behavior**
I shoud get all of the values to view in dropdown

**Expected/desired behavior**
Getting next batch of values when scroll down (like infinite scroll in Select2 Jquery plugin)

**Comment by vreno** [comment]
+1

**Comment by LordRayuga** [comment]
+1

**Comment by nukec** [comment]
+1

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
