### ISSUE TITLE
Preventing default load of lists on click of auto complete text box

### ISSUE THREAD

**Issue by mailmrmanoj** [ng2-ui/auto-complete#280]
Is there any way to make **ng1-ui/auto-complete** to behave as normal text box until I type to see the list of suggestions.
Like [Autocomplete Directive Test - Observable Source](http://plnkr.co/edit/ExzNSh?p=preview) ie.,hide the dropdown initially

**Comment by allenhwkim** [comment]
Yes, possible, but not implemented yet.
We need to introduce a new property. e.g, `show-dropdown-on-focus` with value of true or false.

**Comment by mailmrmanoj** [comment]
Can we expect in the next release?

**Comment by igorrius** [comment]
Fixed in https://github.com/ng2-ui/auto-complete/pull/283

**Comment by mailmrmanoj** [comment]
Thanks
