### ISSUE TITLE
Not able to run autocomplete on a search box

### ISSUE THREAD

**Issue by nikhil5467** [ng2-ui/auto-complete#282]
**IMPORTANT**
_Please be specific with an example. An issue with_ **no example may be closed**.

**Steps to reproduce and a minimal demo**

  - _What steps should we try in your demo to see the problem?_
Just click on the text box having the placeholder bank
  - _Plunker example(REQUIRED)_
https://plnkr.co/edit/6CKmpe5ohT6MmatN61Uh
  - _If you cannot reproduce an issue with a plunker example, it's your environmental issue_

**Current behavior**
When I am trying to enter some text in the input text box i am getting error
  - Invalid type of source, must be a string.
**Expected/desired behavior**

  - It should show the filtered result based on the characters I am typing

**Other information**

  -

**Comment by allenhwkim** [comment]
plunker not working. Please resubmit the issue with clear instruction to reproduce your error.

**Comment by nikhil5467** [comment]
I am implementing the same ng2 auto complete example present at this link
https://github.com/ng2-ui/auto-complete. But when i am implementing it I am getting error on console showing constructor is not defined from the line this.source.constructor === array,and when i comment that line the page loads and as I click on the text box to type something I get an error saying invalid type of keyword : not string like that
I don't know why Plunker is not working ,I have added the same code which I have in my system working.
