### ISSUE TITLE
bug(output): using another form-control makes auto-complete fail (solution)

### ISSUE THREAD

**Issue by AmitMY** [ng2-ui/auto-complete#289]
**Current behavior**

  - When using this library with `ionic`, on `ion-input`, which is already a form control, the `$event` value is taken from that control, so it just gives a string as the event on change.

**Expected/desired behavior**

  - While the current behavior is fine on native inputs, it is not fine on custom control elements, so I would like to ask for another output, like `(itemSelected)` that is strictly a part of this directive, so I will most certainly know that the object coming in the event is yours.

**Other information**

  - Using with ionic

**Comment by AmitMY** [comment]
**Usage**

```
<ion-input auto-complete [source]="addressSource" [list-formatter]="locationToString"
                       (valueChanged)="setLocation($event)"
                       [placeholder]="'pages.location.placeholder' | translate"></ion-input>
```

**Comment by almothafar** [comment]
Since it is working fine in native, it should be something from your side to wrap this native input with your own code to handle ionic, I think this is out of this project scope
