### ISSUE TITLE
display property formatter

### ISSUE THREAD

**Issue by lauhin** [ng2-ui/auto-complete#290]
Hi guys,

Is it possible to add a formatter, like list-formatter or value-formatter, for displaying the selected field?

Thanks in advance.

Laurent

**Comment by crh225** [comment]
doesn't value-formatter accomplish this?

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
