### ISSUE TITLE
Bootstrap 4 beta 1 - Validation form and errors

### ISSUE THREAD

**Issue by rsaenen** [ng2-ui/auto-complete#294]
Hi,
In order to validate a form, errors with BS4-beta1 is wrapped with a div.invalid-feedback.
Angular adds to input the following classes:
* ng-valid/ng-invalid
* ng-pristine/ng-dirty

It's easy to display the div.invalid-feedback if the input has class ng-invalid with the selector .ng-invalid ~ .invalid-feedback.

However, autocomplete wraps the input in a div.ngui-auto-complete-wrapper.
Do you think it's possible to bind input classes (only ng-invalid to begin) to the div.ngui-auto-complete-wrapper ?

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
