### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by lenpino** [ng2-ui/auto-complete#295]
Trying to recreate the http://plnkr.co/edit/ExzNSh?p=preview example throws the following everytime I type a letter in the input:

NguiAutoCompleteComponent.html:16 ERROR TypeError: Cannot read property 'length' of undefined
    at Object.View_NguiAutoCompleteComponent_2._co (NguiAutoCompleteComponent.html:17)

Using Angular 4.3.x (webpack)

**Comment by sh4ka** [comment]
Hi, would you be so kind of sharing your code in plunk or similar?
Thanks.
