### ISSUE TITLE
Copy pasting values into auto-complete field doesn't work

### ISSUE THREAD

**Issue by malchijah** [ng2-ui/auto-complete#298]
Copy pasting values into auto-complete field doesn't show the auto-complete list of values. Instead 'no records found' text is displayed even though values exist. If after pasting, you press 'backspace' or any key, the autocomplete list works. But right after you paste you only see 'no records found' text unless you trigger the keyboard event by hitting spacebar or any other key.

**Comment by malchijah** [comment]
Able to reproduce it here. Try pasting 'Asia 1'.
http://plnkr.co/edit/F9nrWp?p=preview

**Comment by almothafar** [comment]
The name is `Asia` not `Asia 1` the formatter adding `id` to what you see `<span style='color:red'>${data.name} ${data.id} </span>`  so this is why it is showing Asia 1 

Do you mean you want to search cross the object?
