### ISSUE TITLE
customSelected Event not firing

### ISSUE THREAD

**Issue by crh225** [ng2-ui/auto-complete#300]
**IMPORTANT**
_Please be specific with an example. An issue with_ **no example may be closed**.
customSelected Event not firing
**Steps to reproduce and a minimal demo**
http://plnkr.co/edit/01AH3EEKWq168LXo2zcs?p=preview

When I type in something that is not in the dropdown list, should this fire off this changed event.
![image](https://user-images.githubusercontent.com/19475195/32016574-e8fd261c-b989-11e7-9a61-d0ac2ab984bf.png)

I would expect to see the Case 3 message in the console:
![image](https://user-images.githubusercontent.com/19475195/32016605-faf457e6-b989-11e7-87fc-ac60af4c42b4.png)

**Comment by lajos93** [comment]
Did you solve this issue?

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
