### ISSUE TITLE
how to clear selection with [accept-user-input]=false

### ISSUE THREAD

**Issue by crh225** [ng2-ui/auto-complete#301]
**IMPORTANT**
_Please be specific with an example. An issue with_ **no example may be closed**.

**Steps to reproduce and a minimal demo**
http://plnkr.co/edit/D7d8uHG9XQfpsV0LuqcG?p=preview

**Current behavior**
step 1: select Asia
step2: clear out textbox. 
step3: **create a blur event by clicking outside the textbox**
step3: notice how it gets repopulated with Asia.

**Comment by crh225** [comment]
this is separate from https://github.com/ng2-ui/auto-complete/issues/277, as I want to clear the value out completely.

**Comment by crh225** [comment]
It appears it is related to a combination of [list-formatter]="autocompleListFormatter" and accept-user-input=false

**Comment by crh225** [comment]
it seems to be related to this bit of code:
`if (_this.inputEl && hasRevertValue && _this.acceptUserInput === false && currentItem === null) {
                    _this.selectNewValue(_this.revertValue);
                }
                else if (_this.inputEl && _this.acceptUserInput === true && typeof currentItem === "undefined" && event && event.target.value) {
                    _this.enterNewText(event.target.value);
                }`

**Comment by almothafar** [comment]
I think you need to use `select-on-blur`

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
