### ISSUE TITLE
how to set max height of list ?

### ISSUE THREAD

**Issue by suresh2018** [ng2-ui/auto-complete#303]
how to set max height of list ?

**Comment by pravinrahurkar-tudip** [comment]
@suresh2018,

Please try this CSS:

ng2-auto-complete{
  max-height: 150px;
  overflow-y: auto;
}

**Comment by suresh2018** [comment]
i try this already it's not working

**Comment by suresh2018** [comment]
Angular 2 application .
i m using ng2-auto-complete on the PopUp modal.

**Comment by iamtracy** [comment]
Worked for an Angular 4 (angular-cli) app by placing @pravinrahurkar-tudip code in style.scss, should work in style.css.

**Comment by kavishsoam** [comment]
i am facing this same problem, unable to set a minimum heigth to my autocomplete list. please help
