### ISSUE TITLE
Screen is very sluggish when more than 100 autocomplete in my single page.

### ISSUE THREAD

**Issue by aminsmartsense** [ng2-ui/auto-complete#308]
**IMPORTANT**
I have an one row in table in that uses 6 autocomplete. Whenever I am showing multiple records those time append multiple autocomplete after that page start sluggish and working in very slow timing.

**Comment by Pinank** [comment]
@aminsmartsense Having the same issue in one of my application

**Comment by CaffGeek** [comment]
Just created a PR that might help for this https://github.com/ng2-ui/auto-complete/pull/336

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
