### ISSUE TITLE
Angular 5 support

### ISSUE THREAD

**Issue by pil78** [ng2-ui/auto-complete#310]
Hi, 
according to the migration guide to Angular 5, it is required to use HttpClient from "angular/common/http" instead of Http in "angular/http"
Could you please make this changes.

Yaroslav

**Comment by renanmoraes** [comment]
Same problem with me

**Comment by deeppatidar** [comment]
@pil78 Seems already updated but I am getting this "codelyzer@3.2.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none was installed"

**Comment by almothafar** [comment]
The latest version should be fixing this issue.
