### ISSUE TITLE
Custom filter logic

### ISSUE THREAD

**Issue by KRav007** [ng2-ui/auto-complete#313]
I try to insert a new filter logic  with an observable source.
I need help how to solve this issue, because it's not working exactly. 
What do you think, what I have to change. The list is generate to late on fast keypress.
Is the onchange method, the right way to trigger the autocomple source?
How would you solve this?

http://plnkr.co/edit/PYHJ4LPMGHkf8j6eiM2I?p=preview

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
