### ISSUE TITLE
Problems with the plugin in angular version 5

### ISSUE THREAD

**Issue by renanmoraes** [ng2-ui/auto-complete#315]
`ERROR in ./node_modules/@ngui/auto-complete/dist/auto-complete.js
Module not found: Error: Can't resolve '@angular/http' in '/var/www/lb-enterprise/node_modules/@ngui/auto-complete/dist'
resolve '@angular/http' in '/var/www/lb-enterprise/node_modules/@ngui/auto-complete/dist'
  Parsed request is a module
  using description file: /var/www/lb-enterprise/node_modules/@ngui/auto-complete/package.json (relative path: ./dist)
`

I'm having trouble with the plugin when I use it in angular 5, it looks for the @ angular / http module would you let me know if it's already compatible with the latest version of angular?

**Comment by almothafar** [comment]
This is also with angular version 4+ if you use HttpClient instead of Http
