### ISSUE TITLE
Accepting non-list item with accept-user-input=false

### ISSUE THREAD

**Issue by klawson4311** [ng2-ui/auto-complete#317]
**HTML**

    <input autocomplete="off" ngui-auto-complete formControlName="my_form_control" re-focus-after-select type="text" [source]="list_of_values" [accept-user-input]="false" list-formatter="name" max-num-list="5">

**Current behavior**

Steps to Repeat:
1) Focus
2) Enter to select
3) Backspace
4) Tab away
Result:   First item less 1 character.  
This selects an item NOT in the list.

**Expected/desired behavior**

 Don't allow user to select anything not in the list (accept-user-input = false)

**Comment by almothafar** [comment]
Have you tried to set `[tab-to-select]="false"` anyway I'm not sure what the problem, `accept-user-input` should be true if you want to get user input, isn't?

**Comment by coderundebug12** [comment]
@almothafar read the apis first then comment

**Comment by almothafar** [comment]
@coderundebug12 the title confused me so I thought he wants to accept even with "accept-user-input=true", sorry if was misunderstand, but your comment could be better instead of aggressive one.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
