### ISSUE TITLE
Maintain Display when Selection changes

### ISSUE THREAD

**Issue by ghost** [ng2-ui/auto-complete#323]
**Maintain Display when Selection changes**

   `<input ng2-auto-complete
                               formControlName="category"
                               [source]="categories"
                               select-value-of="id"
                               display-property-name="description"
                               placeholder="Select book category"
                               class="form-control"/>`

**Current behavior**
  - The value in the input assumes _id upon selection.

**Expected/desired behavior**
 - To still have _description_ show as display property while the  formControl value is updated.
- i.e., having a readable description selected but _id passed as value.

 **Also, is there a way to disable the input?**
[disabled] isn't working as expected.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
