### ISSUE TITLE
Custom search in an array of objects

### ISSUE THREAD

**Issue by renanmoraes** [ng2-ui/auto-complete#326]
I need to delete the accents when I perform a search.

For example in my array it looks like this:

```
   objcts = [
      {code: "123", name: "Timothy"},
      {code: "752", name: "Timirim"},
   ];
```

The guy researching "thymus" or "Timo" or "Timó" it should appear for him the same object that is with code 123.

I tried to use the source to do this function but I can not do it. Would you like to do this using your plugin?

_Ahh and thank you for the great work offered to society with this project. Congratulations !_

**Comment by almothafar** [comment]
I think it is out of the scope of this project and too much for it, the only way I see is using the source, not sure why did not worked for you but you maybe can do that logic from server side or something else, translations and aliases are not what this plugin meant to do.
