### ISSUE TITLE
Can't bind to 'source' since it isn't a known property of 'input'

### ISSUE THREAD

**Issue by skaka30** [ng2-ui/auto-complete#328]
Hi,

I tried to integrate the auto-complete, but I got this error : 
`Can't bind to 'source' since it isn't a known property of 'input'.`
`Can't bind to 'loading-template' since it isn't a known property of 'input'.`
`Can't bind to 'source' since it isn't a known property of 'input'. `
`Can't bind to 'loading-template' since it isn't a known property of 'input'.`

I tried to find my mistake but I am not getting. My project folder structure is like parent child, For example Job is my parent component and country is child component. So this auto complete  I want use in child component. But When I use sample code in to my child component shown  above errors. I don't where is my mistake. Please suggest me

Thanks.

**Comment by guanzhiyou** [comment]
Have you solve this problem? I have the same problem

**Comment by skaka30** [comment]
@guanzhiyou  still this issue open

**Comment by allenhwkim** [comment]
If you want to reopen this ticket, please reproduce this issue at https://stackblitz.com.
From my experience, this is the issue of not importing the module properly.

**Comment by sandroweb** [comment]
I have the same problem. You have a solution?
