### ISSUE TITLE
Angular2 ng2-auto-complete display and selection issues

### ISSUE THREAD

**Issue by skaka30** [ng2-ui/auto-complete#329]
I have implemented the Angular 2 ngui-auto-complete component. And related to this i found [example](http://plnkr.co/edit/ExzNSh?p=preview). But the issue I'm facing is, on my auto-complete there multiple dependencies. So for that on selection I want id but I am not getting on selection id.

And one more facing issue is my source is in the form of an object with id as one of the fields. And by following the implementation example of the component, the id is displayed in parenthesis in the dropdown. Is there a way to not display the id in the dropdown?

Here is my HTML code for the auto-complete component:
`<input  class="text-uppercase form-control" ngui-auto-complete [(ngModel)]="shipper.cust_name" [source]="shipperNameSource.bind(this)" value-property-name=null  value-formatter="cust_name" min-chars="1" (change)="updateShipperDetails()"/>
`
My component

`shipperNameSource = (keyword: any): Observable<any[]> => {
    let url: string = 
      'api/getCustomers?selected='+keyword
    if (keyword) {
      return this.http.get(url)
        .map(res => {
            let json = res.json();
            this.customer.id = json.id;
          return json;
        })
    } else {
      return Observable.of([]);
    }
}
`
This is what I get

![](https://i.stack.imgur.com/fB9xX.png)

**Comment by itsashish-patel** [comment]
@skaka30 , Please refer the following solution for your problem

get id based on selection use value change event and you will get selected any object e.g. `(valueChanged)="updateShipperDetails($event)"
`
use "list formatter" attribute to display your property e.g. `list-formatter="cust_name"`
