### ISSUE TITLE
click on items getting input blank 

### ISSUE THREAD

**Issue by chaouiy** [ng2-ui/auto-complete#330]
When user clicks inside the list formatted elements nothing happened (input gets blank). Clicks work only outside html element declared in `autocompleteListFormatter`
```
 autocompleListFormatter = (data: any) => {
    let html = `<p class="d-inline-block" style="padding-top: 10px; cursor:default;"><img class='img-rounded' width='32px' src='${data.picture}'/> <strong class="m-l-xs">${data.first_name} ${data.last_name} </strong></p>`;
    return this._sanitizer.bypassSecurityTrustHtml(html);
  }
```

**Comment by amineparis** [comment]
after tests the problem occurs when clicking on image, Any suggestions to handle this ?

**Comment by almothafar** [comment]
May you please provide a working plunker example?

**Comment by pavankumarkatakam** [comment]
Hi @amineparis , this happens with element HTML content also.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
