### ISSUE TITLE
Don't show the autocomplete list when the textbox is empty

### ISSUE THREAD

**Issue by japolonio** [ng2-ui/auto-complete#331]
Hi, is there a way that autocomplete list will not show when the textbox is empty?

**Steps to reproduce and a minimal demo**

- Clicked the textbox that autocomplete integrated

**Current behavior**

  - There is a list shown when the textbox is empty

**Expected/desired behavior**

  - There should be no list shown unless the user start typing on the textbox

**Other information**

  -

**Comment by dsantanac** [comment]
option:
min-chars="1"

**Comment by crico** [comment]
Seems that min-chars only works for remote sources.
