### ISSUE TITLE
Exact Matching List only

### ISSUE THREAD

**Issue by PrabhatKh** [ng2-ui/auto-complete#332]
How do I list the dropdown with only the EXACT match from the datalist?

  - 

**Expected/desired behavior**

  - 

**Other information**

  -

**Comment by almothafar** [comment]
I don't think this is what "autocomplete" meant to do, I'm not really sure what do you mean by "exact".

Anyways, have you tried to work with "Observable Source"?

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
