### ISSUE TITLE
Does not get close on click outside if used in the modal popup

### ISSUE THREAD

**Issue by pravinrahurkar-tudip** [ng2-ui/auto-complete#333]
**Does not get close on click outside if used in the modal popup**

**Steps to reproduce**

  - Add the auto-filter dropdown in the bootstrap modal popup.
  - It opens the list but does not get closed on click outside.
  - It is working fine on the other place but on bootstrap modal popup it's not working.

**Current behavior**

  - Not getting close on the bootstrap modal popup but working on the simple page.

**Expected/desired behavior**
  -  After focus out or click outside it should hide the dropdown list on the bootstrap modal popup.

Any help is very much appreciated.

**Comment by almothafar** [comment]
I'm working with auto-complete inside modal (https://github.com/shlomiassaf/ngx-modialog) and have no such error like this, may you please provide a plunker example, since bootstrap is something I imagine is easy to do.

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
