### ISSUE TITLE
[open-on-focus]  attributes cannot bind in version 1.0.2 or 0.13.0, but it's ok in version 0.16.0.

### ISSUE THREAD

**Issue by zoeylee** [ng2-ui/auto-complete#337]
**IMPORTANT**
```
<div ngui-auto-complete
                [source]="arrayOfStrings"
                [accept-user-input]="true"
                [open-on-focus]="false"
                (valueSelected)="add($event)"
                (ngModelChange)="myCallback1($event)"
                (customSelected)="customCallback($event)"
                placeholder="enter text">
```

**core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'open-on-focus' since it isn't a known property of 'div'. ("  
             [source]="arrayOfStrings"
                [accept-user-input]="true"
                [ERROR ->][open-on-focus]="false"
                (valueSelected)="add($event)"
                (ngModelChange)"): ng:///PagesRoutingModule/CreateStatusProbeModalComponent.html@100:16**

**Steps to reproduce and a minimal demo**
 ```
  a) npm install @ngui/ngui
  b) import { NguiAutoCompleteModule } from '@ngui/auto-complete';
      imports: [
          NguiAutoCompleteModule
      ]
  c) <div ngui-auto-complete
                [source]="arrayOfStrings"
                [accept-user-input]="true"
                [open-on-focus]="false"
                (valueSelected)="add($event)"
                (ngModelChange)="myCallback1($event)"
                (customSelected)="customCallback($event)"
                placeholder="enter text">

```
**Other information**
  ```
it's ok when I installed 0.16.0.
  npm install @ngui/auto-complete@0.16.0 --save
```

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
