### ISSUE TITLE
Is there a way to disable sending request on text change

### ISSUE THREAD

**Issue by nukec** [ng2-ui/auto-complete#339]
And rather do it on enter inside of textbox?

**Comment by almothafar** [comment]
I'm not sure if I'm getting your problem correctly but I think you have the control for that.
https://github.com/ng2-ui/auto-complete#attributes

**Comment by jderuere** [comment]
I cant figure out which control I have to use. In my use case, I would like to autocomplete after the user hit "enter" or "tab", I don't know if there is a way to do this?

**Comment by nukec** [comment]
@jderuere the way to go is by increasing debounce time to 1-2 seconds in settings, since there is no way to invoke search on enter as of now

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
