### ISSUE TITLE
ERROR in Metadata version mismatch with angular 4.3.6

### ISSUE THREAD

**Issue by ghachemsaif** [ng2-ui/auto-complete#364]
Hello,
Im working on angular 4.3.6 project. And im tried to use ngui auto-complete. I used both versions 2.0.0 and 1.0.2 and always im getting the same probleme : 

ERROR in Metadata version mismatch for module C:/MyProject/node_modules/@ngui/auto-complete/dist/index.d.ts,
found version 4, expected 3, resolving symbol AppModule in C:/MyProject/src/app/app.module.ts, resolving symb
ol AppModule in C:/MyProject/src/app/app.module.ts

**Comment by almothafar** [comment]
What is your package.json content, it seems you mix some angular versions, also I suggest deleting `node_modules` and try again, and another recommendation to use yarn instead of npm.

**Comment by ghachemsaif** [comment]
> What is your package.json content, it seems you mix some angular versions, also I suggest deleting `node_modules` and try again, and another recommendation to use yarn instead of npm.

Hi,
Thanks for your support ! But im not mixing my angular versions, here is my package.json : 
`{
  "name": "webapp-ng",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "4.3.6",
    "@angular/common": "4.3.6",
    "@angular/compiler": "4.3.6",
    "@angular/core": "4.3.6",
    "@angular/forms": "4.3.6",
    "@angular/http": "4.3.6",
    "@angular/platform-browser": "4.3.6",
    "@angular/platform-browser-dynamic": "4.3.6",
    "@angular/router": "4.3.6",
    "@condor/common": "0.2.0",
    "@condor/components": "0.2.0",
    "@condor/services": "0.2.0",
    "@condor/template": "0.2.0",
    "@condor/themes": "0.2.0",
    "@ngui/auto-complete": "^1.0.2",
    "angular-ide": "^0.9.44",
    "angular2-logger": "^0.6.0",
    "core-js": "^2.5.7",
    "d3": "^4.13.0",
    "d3-array": "^1.2.4",
    "d3-axis": "^1.0.12",
    "d3-brush": "^1.0.6",
    "d3-line": "0.0.1",
    "d3-scale": "^2.1.2",
    "d3-selection": "^1.3.2",
    "d3-shape": "^1.2.2",
    "d3-time-format": "^2.1.3",
    "d3-zoom": "^1.7.3",
    "lodash": "^4.17.10",
    "ng2-auto-complete": "^0.12.0",
    "ng2-completer": "^1.6.3",
    "ngx-cookie-service": "^1.0.9",
    "primeng": "4.2.1",
    "rxjs": "^5.5.12",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "1.2.6",
    "@angular/compiler-cli": "4.3.6",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.117",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.4.2"
  },
  "styles": [
    "styles.css"
  ]
}
`

**Comment by almothafar** [comment]
@ghachemsaif mixing could be done because other dependencies, it is hard to tell unless you do more debugging around this, what I mean with mixing, I mean any dependencies, look at your package.json you can see you have `"ng2-auto-complete": "^0.12.0"` and `"@ngui/auto-complete": "^1.0.2"` 

The error itself describe everything actually.
