### ISSUE TITLE
Still need rxjs-compat

### ISSUE THREAD

**Issue by rbirkgit** [ng2-ui/auto-complete#376]
**IMPORTANT**
Latest version still requires rxjs-compat. You get an error without it. Itw as supposed to be upgraded to rxjs 6, but is not.

**Steps to reproduce and a minimal demo**

Build your app and see error.

**Current behavior**

ERROR in ./node_modules/ng2-auto-complete/dist/ng2-auto-complete.js
Module not found: Error: Can't resolve 'rxjs/add/operator/map' in 'D:\Git\provisioning-ui\node_modules\ng2-auto-complete\dist'

**Expected/desired behavior**

Import in latest version should be changed to support rxjs 6:

import { map } from 'rxjs/operators';

**Other information**

  -

**Comment by catherinemarston** [comment]
Any updates on this? 

Thank you,

Catherine

**Comment by almothafar** [comment]
This issue is stale. Please consider opening a new issue with details for the latest version if you are still facing the same issue or need improvement.

Closing it.
