### ISSUE TITLE
Angular 9(Ivy): Error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

### ISSUE THREAD

**Issue by ajay-verma-01** [ng2-ui/auto-complete#383]
**IMPORTANT**
Angular 9(IVY) - Error when running ng server
ERROR in node_modules/@ngui/auto-complete/dist/auto-complete.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

**Steps to reproduce and a minimal demo**
1. npm install @ngui/auto-complete
2. import NguiAutoCompleteModule in AppModule
3. ng serve

**Current behavior**

Error

**Expected/desired behavior**

Should build and work

**Comment by webcat12345** [comment]
It's working with angular 9, ivy renderer.

```
core.js:5828 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'id' of undefined
```
Any clue?

**Comment by webcat12345** [comment]
I have Not-completed-and-pending PR here https://github.com/ng2-ui/auto-complete/pull/384

If guys open green light on my way, I would keep moving and complete PR.

**Comment by almothafar** [comment]
@webcat12345 I'm not sure if I can go with testing before publishing for this, but if you know what exactly needed and you can contribute to fix any issue, that surely appreciated, and I'll try to publish it.

**Comment by webcat12345** [comment]
@almothafar Finally, I have updated my PR #384 and it is ready to be merged. Please review it and let me know. Thanks.

**Comment by almothafar** [comment]
Thanks, @webcat12345 , but may you please check my comments? maybe I'm missing something, and these comments just a quick review.
Also, May you please mention any breaking changes in https://github.com/ng2-ui/auto-complete/blob/master/CHANGELOG.md?

**Comment by webcat12345** [comment]
Thanks @almothafar 

I have updated PR according to your commit and also added short description of new version to **CHANGELOG.md**.

Could you please review it again when you have time?
Thanks.

**Comment by aarukarthiga** [comment]
any updates ?

**Comment by almothafar** [comment]
@aarukarthiga Corona situation in Jordan did full lockdown for the country, and ISP is not moving to connect my fiber back, I got a temporary 4G connection so I'll try to do it today.

**Comment by sampath-karupakula** [comment]
> @aarukarthiga Corona situation in Jordan did full lockdown for the country, and ISP is not moving to connect my fiber back, I got a temporary 4G connection so I'll try to do it today.

Hi Almothafar, yea, corona issue is making lifes worse than before.  hope you are safe and secure. Even I am waiting for the new release. could you please if possible ?

**Comment by sampath-karupakula** [comment]
any update on this ?

**Comment by almothafar** [comment]
@webcat12345  @sampath-karupakula 
May you please check version 3.0.0?

**Comment by tpapagiannis** [comment]
The same problem, no compilation with ivy.
When an update will be ready ?

**Comment by almothafar** [comment]
Did you try version 3.0.0? if yes, do you have issues?

**Comment by tpapagiannis** [comment]
Hi, thank you, version 3.0.0 works .
Thanks again.
