### ISSUE TITLE
For angular 9 its not supporting 

### ISSUE THREAD

**Issue by aarukarthiga** [ng2-ui/auto-complete#385]
This likely means that the library (@ngui/auto-complete) which declares NguiAutoCompleteModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by almothafar** [comment]
Duplicate if #383
