### ISSUE TITLE
Support for Angular 17

### ISSUE THREAD

**Issue by kushal-novopay** [ng2-ui/auto-complete#431]
Does it support Angular 17 out of the box?
Edit: It does not. Supports only till 9. This package needs an upgrade

**Comment by gigo6000** [comment]
Is there any good replacement option for Angular 17?

**Comment by almothafar** [comment]
@ajmal1971 you should have a fork, or contribute to the repo, instead of copy/paste as now you don't give credits in commits that is done to this repo.

**Comment by ajmal1971** [comment]
I will delete the new repository. I'll contribute to the repo.

**Comment by almothafar** [comment]
I am working on it right now, I reached 13 now, and it is still in progress,

**Comment by almothafar** [comment]
Please try now and check if everything is OK
